"""Configuration for the calculator (defaults)."""
CALCULATOR_LOG_DIR = "logs"
CALCULATOR_LOG_FILE = "calculator.log"
CALCULATOR_LOG_PATH = f"{CALCULATOR_LOG_DIR}/{CALCULATOR_LOG_FILE}"
CALCULATOR_HISTORY_FILE = "history.csv"
CALCULATOR_HISTORY_PATH = f"{CALCULATOR_LOG_DIR}/{CALCULATOR_HISTORY_FILE}"
CALCULATOR_DEFAULT_PRECISION = 2
